logging:
  level:
    root: INFO

endpoints:
  actuator:
    sensitive: false

management:
  security:
    enabled: false

resilience4j.circuitbreaker:
  instances:
    my-breaker:
      registerHealthIndicator: true
      slidingWindowSize: 100
    backendB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
